### ISSUE TITLE
The readme only explains how to duplicate the project, not what it does or how to use it.

### ISSUE THREAD

**Issue by Razpudding** [lhafkamp/jouliette-telegram-bot#5]
While it is now possible for a dev to duplicate the project, it's not clear to end users what you can do with it. I think for this project it would be good to describe what it means when a boat is "offline". But also how users can interact with the bot. Something like this:
Do A to add the bot
The bot will now send B everytime condition C is met
If you want to turn of notifications for condition C, do D.

**Comment by lhafkamp** [comment]
I updated the README in 35607ad.
